import time, json, requests
from pathlib import Path

from backend.director_core import main as director_run
from backend.critic import evaluate

PLAN_PATH = Path("backend/data/autopilot/director_plan.json")

API_URL = "http://127.0.0.1:8000/api/product-pack"

def loop():
    while True:
        print("=== DIRECTOR THINKING ===")
        director_run()

        if PLAN_PATH.exists():
            plan = json.load(open(PLAN_PATH))
            topic = plan.get("focus", "AI product")

            print("=== BUILDER EXECUTION ===")

            try:
                response = requests.post(API_URL, json={
                    "topic": topic,
                    "niche": "Content Monetization",
                    "tone": "Premium",
                    "buyer": "Beginners",
                    "promise": "make money quickly",
                    "bonus": "templates",
                    "notes": "auto generated by director"
                })
                result = response.json()
                text = str(result)
            except Exception as e:
                print("Builder error:", e)
                text = str(plan)

            print("=== CRITIC EVALUATING ===")
            scores = evaluate(text)
            print(scores)

        time.sleep(60)

if __name__ == "__main__":
    loop()
