from __future__ import annotations

import importlib
import inspect
from typing import Any, Dict, Optional

def _try_money_engine(payload: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    candidate_modules = [
        "app.engines.money_engine",
        "backend.app.engines.money_engine",
    ]
    candidate_functions = [
        "run_money_mode",
        "run_money_engine",
        "generate_money_product",
        "build_money_product",
        "generate_product",
        "create_product",
        "run",
    ]

    for module_name in candidate_modules:
        try:
            module = importlib.import_module(module_name)
        except Exception:
            continue

        for fn_name in candidate_functions:
            fn = getattr(module, fn_name, None)
            if not callable(fn):
                continue
            try:
                sig = inspect.signature(fn)
                if len(sig.parameters) == 0:
                    result = fn()
                else:
                    result = fn(payload)
                if isinstance(result, dict):
                    return result
            except Exception:
                continue
    return None

def synthesize_product(payload: Dict[str, Any]) -> Dict[str, Any]:
    existing = _try_money_engine(payload)
    if existing:
        return existing

    title = payload.get("title") or payload.get("topic") or "Zerenthis Product"
    summary = payload.get("summary") or payload.get("promise") or "A premium offer generated by Zerenthis."
    price = int(payload.get("price") or 29)

    return {
        "title": title,
        "summary": summary,
        "steps": payload.get("steps") or [
            "Pick a high-demand angle",
            "Use the system as written",
            "Publish the offer",
            "Drive short-form traffic",
            "Convert clicks into sales"
        ],
        "price": price,
        "checkout_link": payload.get("checkout_link", ""),
        "sales_copy": payload.get("sales_copy", ""),
        "topic": payload.get("topic") or title,
        "niche": payload.get("niche", "General"),
        "file": payload.get("file")
    }

