from __future__ import annotations

import html
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

BASE_DIR = Path(__file__).resolve().parents[2]
STOREFRONT_DIR = BASE_DIR / "outputs" / "storefront"
STOREFRONT_DIR.mkdir(parents=True, exist_ok=True)

def slugify(text: str) -> str:
    text = (text or "").strip().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-") or "product"

def build_storefront(product: Dict[str, Any], publish: Dict[str, Any], traffic: Dict[str, Any]) -> Dict[str, Any]:
    title = product.get("title", "Untitled Product")
    summary = product.get("summary", "")
    price = publish.get("price", 29)
    checkout_link = publish.get("checkout_link", "")
    slug = publish.get("slug") or slugify(title)

    bullets = product.get("steps") or []
    bullet_html = "".join(f"<li>{html.escape(str(x))}</li>" for x in bullets)

    hooks = traffic.get("hooks") or []
    hook_html = "".join(f"<li>{html.escape(str(x))}</li>" for x in hooks[:5])

    sales_copy = html.escape(str(publish.get("sales_copy", ""))).replace("\n", "<br>")

    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(title)}</title>
<style>
body {{ font-family: Arial, sans-serif; background:#0b1020; color:#f5f7ff; margin:0; padding:0; }}
.wrap {{ max-width:900px; margin:0 auto; padding:40px 24px; }}
.card {{ background:#121933; border:1px solid #283252; border-radius:16px; padding:24px; margin-bottom:20px; }}
h1,h2 {{ margin-top:0; }}
.cta {{
    display:inline-block; background:#1f6feb; color:white; text-decoration:none;
    padding:14px 20px; border-radius:12px; font-weight:bold;
}}
.small {{ color:#b9c3e1; }}
ul {{ line-height:1.7; }}
code {{ background:#0f1530; padding:2px 6px; border-radius:6px; }}
</style>
</head>
<body>
<div class="wrap">
  <div class="card">
    <div class="small">Zerenthis Storefront</div>
    <h1>{html.escape(title)}</h1>
    <p>{html.escape(summary)}</p>
    <p><strong>Price:</strong> ${price}</p>
    <p><a class="cta" href="{html.escape(checkout_link)}" target="_blank">Buy Now</a></p>
  </div>

  <div class="card">
    <h2>What you get</h2>
    <ul>{bullet_html}</ul>
  </div>

  <div class="card">
    <h2>Sales Copy</h2>
    <p>{sales_copy}</p>
  </div>

  <div class="card">
    <h2>Traffic Hooks</h2>
    <ul>{hook_html}</ul>
  </div>

  <div class="card">
    <div class="small">Generated by Zerenthis</div>
    <p>Checkout link: <code>{html.escape(checkout_link)}</code></p>
  </div>
</div>
</body>
</html>
"""

    out = STOREFRONT_DIR / f"{slug}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.html"
    out.write_text(page, encoding="utf-8")

    return {
        "ok": True,
        "storefront_file": str(out).replace("\\", "/"),
        "slug": slug
    }
