from fastapi import APIRouter, Body
from datetime import datetime, timezone
from pathlib import Path
import uuid, random, json

router = APIRouter(prefix="/api/command", tags=["command"])

BASE = Path(__file__).resolve().parents[2]
OUT = BASE / "backend/outputs"
OUT.mkdir(parents=True, exist_ok=True)

def now():
    return datetime.now(timezone.utc).isoformat()

# ---------------- DIRECTOR ----------------
def director(prompt):
    formats = ["viral short","youtube episode","animated skit"]
    tones = ["chaotic","funny","dramatic","absurd"]
    return {
        "format": random.choice(formats),
        "tone": random.choice(tones)
    }

# ---------------- RESEARCHER ----------------
def researcher():
    hooks = [
        "Nobody expected this to happen",
        "This got out of control instantly",
        "This is the funniest thing online right now"
    ]
    twists = ["betrayal","shock reveal","public embarrassment"]
    return random.choice(hooks), random.choice(twists)

# ---------------- WRITER ----------------
def writer(prompt, hook, twist):
    characters = ["Alpha","Nova","Blitz","Zara"]
    script = [
        f"HOOK: {hook}",
        f"{characters[0]} enters confidently.",
        f"{characters[1]} challenges them immediately.",
        f"Twist happens: {twist}.",
        "Everything explodes into chaos.",
        "Cliffhanger ending."
    ]
    return script, characters

# ---------------- CRITIC ----------------
def critic(script):
    score = random.uniform(6,10)
    return score >= 8.2, round(score,2)

# ---------------- REFINER LOOP ----------------
def refine(prompt):
    best = None
    for _ in range(8):
        hook, twist = researcher()
        script, chars = writer(prompt, hook, twist)
        ok, score = critic(script)

        if ok:
            best = (script, chars, hook, twist, score)
            break

    return best

# ---------------- PRODUCER ----------------
def produce(script, chars, hook):
    shots = [f"Scene: {line}" for line in script]
    captions = [hook, "Follow for next episode"]
    return shots, captions

# ---------------- EXPANSION ----------------
def expand(title, twist):
    return {
        "youtube": f"{title} full episode based on {twist}",
        "podcast": f"Discussion inside {title}",
        "comic": f"Story arc about {twist}",
        "game": f"Interactive chaos game with elimination mechanics"
    }

@router.post("/run")
def run(payload: dict = Body(...)):
    prompt = payload.get("prompt","")

    decision = director(prompt)
    result = refine(prompt)

    if not result:
        return {"status":"failed","reason":"no strong output generated"}

    script, chars, hook, twist, score = result

    shots, captions = produce(script, chars, hook)
    expansion = expand(prompt, twist)

    file = f"{uuid.uuid4().hex[:6]}.json"
    (OUT / file).write_text(json.dumps({
        "script": script,
        "shots": shots,
        "captions": captions,
        "expansion": expansion
    }, indent=2))

    return {
        "status":"ok",
        "phase":"hidden team generator",
        "result":{
            "title": prompt,
            "quality_score": score,
            "file": f"/api/file/{file}",
            "summary": "Fully refined output generated by internal system"
        }
    }
